apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: thinknyx
  name: thinknyx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: thinknyx
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: thinknyx
    spec:
      containers:
      - image: thinknyx/demoapp:v1
        name: demoapp
        resources: {}
status: {}
