apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: thinknyx
  name: thinknyx
spec:
  replicas: 3 
  selector:
    matchLabels:
      app: thinknyx
  strategy: {}
  template:
    metadata:
      labels:
        app: thinknyx
    spec:
      containers:
      - image: thinknyx/demoapp:v1
        name: demoapp
        ports:
        - containerPort: 80
status: {}
